//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPSC
    {
        public int IDCTPSC { get; set; }
        public int IDPSC { get; set; }
        public int IDVTPT { get; set; }
        public int IDTienCong { get; set; }
        public int SoLuong { get; set; }
    
        public virtual PhieuSuaChua PhieuSuaChua { get; set; }
        public virtual TienCong TienCong { get; set; }
        public virtual VTPT VTPT { get; set; }
    }
}
