//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhap
    {
        public int IDPN { get; set; }
        public int IDVTPT { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGiaNhap { get; set; }
        public Nullable<int> TonKho { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual VTPT VTPT { get; set; }
    }
}
