//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.CTPhieuNhaps = new HashSet<CTPhieuNhap>();
        }
    
        public int IDPN { get; set; }
        public int IDTK { get; set; }
        public Nullable<int> IDNCC { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> TongSL { get; set; }
        public System.DateTime NgayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhap> CTPhieuNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual TaiKhoanNhanVien TaiKhoanNhanVien { get; set; }
    }
}
