//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuTien
    {
        public int IDPTT { get; set; }
        public int IDXe { get; set; }
        public System.DateTime NgayThuTien { get; set; }
        public decimal SoTienThu { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
