//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiepNhanXe
    {
        public int IDTN { get; set; }
        public int IDXe { get; set; }
        public int IDTK { get; set; }
        public System.DateTime NgayTiepNhan { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual TaiKhoanNhanVien TaiKhoanNhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
